### ISSUE TITLE
Support for nvidia proprietary drivers

### ISSUE THREAD

**Issue by ferion11** [ferion11/PCSX2_Appimage#1]
Support for nvidia proprietary drivers:
- Remove nouveau module.
- add lib32-nvidia-utils for recent.
- or add lib32-nvidia-390xx-utils for legacy.

**Comment by ferion11** [comment]
proprietary drivers for NVIDIA included in:
* pcsx2_NVIDIA-1.5.0dev-x86_64.AppImage
* pcsx2_NVIDIA390xx-1.5.0dev-x86_64.AppImage
* pcsx2_NVIDIA340xx-1.5.0dev-x86_64.AppImage

([NVIDIA's legacy card list](https://www.nvidia.com/en-us/drivers/unix/legacy-gpu/))
NOTE 1: The 340xx last supported Xorg version is 1.20
NOTE 2: I have just removed nouveau and installed NVIDIA proprietary drivers. Maybe it will need more work.

**Comment by ferion11** [comment]
No bugs reported till this moment, so closing for now.

**Comment by MahdiBaghbani** [comment]
Hi, I have NVIDIA GTX 750 Ti with driver v470 and Ubuntu 20.04, I can help you for testing .

**Comment by ferion11** [comment]
> Hi, I have NVIDIA GTX 750 Ti with driver v470 and Ubuntu 20.04, I can help you for testing .

Thanks, but the next official PCSX2 release will also have an official appimage. So we will support the official release instead of this repository.
