### ISSUE TITLE
Asking for update

### ISSUE THREAD

**Issue by ferion11** [ferion11/PCSX2_Appimage#3]
If the AppImage gets old (with the last git), just ask for one update here.

**Comment by Csokis** [comment]
Please, update the AppImage, because I can't compile "native" PCSX2 on Ubuntu 20.04.1. :( Thank You! :)

**Comment by ferion11** [comment]
The last stable is still the 1.6.0:
https://github.com/ferion11/PCSX2_Appimage/releases/tag/continuous-1.6.x

and the last git already have a 64bits version now, so i need to change the AppImage to pure 64bits too. I'm waiting a little more for a more stable git version. So, be a little more patient with this. There are a lot of others changes that need adaptation too (github acess, travis-ci build, release building, the world is upside down, i don't know why people like to make so many changes on the lookdown and let nothing old working again).

**Comment by Csokis** [comment]
Then I wait patiently! :) Thank You!

**Comment by ferion11** [comment]
Discontinued in favor of the official 64bis native version.
