### ISSUE TITLE
Missing plug-in on every run error

### ISSUE THREAD

**Issue by casasfernando** [ferion11/PCSX2_Appimage#5]
I downloaded the latest AppImage build and almost everything works except for the fact that every time I run it I get an error regarding a missing plug-in that takes me to the plug-in configuration screen.
There I have to change the sound plug-in manually (the default is the null plug-in -meaning no sound-) and save the changes. Afterwards I can boot the game successfully.
This is really inconvenient if pcsx2 is started with the —no-gui option since even after manually changing the plug-in configuration  the game will not boot automatically.

OS: Debian 10 (Buster) x86_64

Let me know if you need any logs or any further information.
Except for this everything else seems to work fine.

Thanks for all your work.

**Comment by ferion11** [comment]
This default selection of sound "null plug-in" is just on the first time execution. If you change it at the wizard that show on the first time, then the configuration will be saved. The first execution is for configuration, avoid using "--nogui" option. But all of this came from the PCSX2 itself, no from the AppImage. I have tested it here, and the sound configuration worked with 3 execution using "--nogui --nodisc".
If I have understand it wrong, could you make clear the steps to replicate the same behavior here?

**Comment by casasfernando** [comment]
I tried the no-gui option only after I ran it with a gui for several times, but even with the gui I get this everytime.
As for repro steps all I do is:

1- download the latest AppImage.
2- run it and configure it for the first time (bios path, plugins, etc.)
3- play any game
4- exit pcsx2 from the menu
5- run it again, I get the error and I’m sent to the plugins configuration dialog.

Let me collect the exact error I get and the pcsx2 log that I think may help to better understand what is going on.
I can also try to remove the pcsx2 configuration directory and start fresh but I think I already did that.

Will come back with more details.
Thanks

**Comment by ferion11** [comment]
Try in this order first:
1- download the latest AppImage.
2- run it and configure it for the first time (bios path, plugins, etc.)
3- Exit the PCSX2 to make sure it have saved the configuration
4- Start it again
5- play any game
6- exit pcsx2 from the menu
7- run it again, I get the error and I’m sent to the plugins configuration dialog.

And see if the same error happen.

**Comment by casasfernando** [comment]
> Try in this order first:
> 1- download the latest AppImage.
> 2- run it and configure it for the first time (bios path, plugins, etc.)
> 3- Exit the PCSX2 to make sure it have saved the configuration
> 4- Start it again
> 5- play any game
> 6- exit pcsx2 from the menu
> 7- run it again, I get the error and I’m sent to the plugins configuration dialog.
> 
> And see if the same error happen.

Will try this and report back, along with the log if the issue happens again.
I guess I should also remove the current configuration directory (.config/PCSX2) and start from scratch with step 1, right?

**Comment by ferion11** [comment]
You can use the same latest AppImage. I just used your preview comment to add more steps. Because the gameplay can do things that isn't normal, so always configure first, exit, start again and see if the configuration is there, if yes then start play. That is what I do on all softwares that I use.

**Comment by casasfernando** [comment]
Ok, I tried again, same issue. This time I collected some screenshots.
What I did:

1- Removed the pcsx2 configuration files.
2- Started pcsx2 again and went through the general configuration steps (plugins, BIOS, etc).
3- Closed pcsx2.
4- Started pcsx2 again, I got the missing plugin error. The error is specific to the video plugin and I think is related to the path being hardcoded somewhere. Since the path changes on every run, the plugin is not found and pcsx2 ask to configure the plugins again.

![Screenshot_2020-03-06_09-41-21](https://user-images.githubusercontent.com/15861819/76068237-15459600-5f91-11ea-8533-aa8db252501a.png)

5- Reconfigured the plugins again.

![Screenshot_2020-03-06_09-44-19](https://user-images.githubusercontent.com/15861819/76068266-24c4df00-5f91-11ea-8407-3955693bbe9b.png)

6- Closed pcsx2 and started it again.

![Screenshot_2020-03-06_09-45-47](https://user-images.githubusercontent.com/15861819/76068321-3dcd9000-5f91-11ea-8634-9841edb51333.png)

Note how everytime pcsx2 is looking for the plugin in a different path.

**Comment by casasfernando** [comment]
Investigated this a little bit more and found that the problem may be related to the plugins path being saved to the ***PCSX2_ui.ini***. Since this path is changing on every run, pcsx2 is not finding the plugins. Look at how the patch changes with every run:

Execution 1:

```
./inis/PCSX2_ui.ini:Langs=/tmp/.mount_pcsx2Npu3aO/usr/lib32/Langs
./inis/PCSX2_ui.ini:PluginsFolder=/tmp/.mount_pcsx2Npu3aO/usr/lib32/pcsx2
./inis/PCSX2_ui.ini:GS=/tmp/.mount_pcsx2Npu3aO/usr/lib32/pcsx2/libGSdx-AVX2.so
./inis/PCSX2_ui.ini:PAD=/tmp/.mount_pcsx2Npu3aO/usr/lib32/pcsx2/libonepad.so
./inis/PCSX2_ui.ini:SPU2=/tmp/.mount_pcsx2Npu3aO/usr/lib32/pcsx2/libspu2x-2.0.0.so
./inis/PCSX2_ui.ini:CDVD=/tmp/.mount_pcsx2Npu3aO/usr/lib32/pcsx2/libCDVDnull.so
./inis/PCSX2_ui.ini:USB=/tmp/.mount_pcsx2Npu3aO/usr/lib32/pcsx2/libUSBnull-0.7.0.so
./inis/PCSX2_ui.ini:FW=/tmp/.mount_pcsx2Npu3aO/usr/lib32/pcsx2/libFWnull-0.7.0.so
./inis/PCSX2_ui.ini:DEV9=/tmp/.mount_pcsx2Npu3aO/usr/lib32/pcsx2/libdev9ghzdrk-0.4.so
```

Execution 2:

```
./inis/PCSX2_ui.ini:Langs=/tmp/.mount_pcsx2SfJUyH/usr/lib32/Langs
./inis/PCSX2_ui.ini:PluginsFolder=/tmp/.mount_pcsx2SfJUyH/usr/lib32/pcsx2
./inis/PCSX2_ui.ini:GS=/tmp/.mount_pcsx2SfJUyH/usr/lib32/pcsx2/libGSdx-AVX2.so
./inis/PCSX2_ui.ini:PAD=/tmp/.mount_pcsx2SfJUyH/usr/lib32/pcsx2/libonepad.so
./inis/PCSX2_ui.ini:SPU2=/tmp/.mount_pcsx2SfJUyH/usr/lib32/pcsx2/libspu2x-2.0.0.so
./inis/PCSX2_ui.ini:CDVD=/tmp/.mount_pcsx2SfJUyH/usr/lib32/pcsx2/libCDVDnull.so
./inis/PCSX2_ui.ini:USB=/tmp/.mount_pcsx2SfJUyH/usr/lib32/pcsx2/libUSBnull-0.7.0.so
./inis/PCSX2_ui.ini:FW=/tmp/.mount_pcsx2SfJUyH/usr/lib32/pcsx2/libFWnull-0.7.0.so
./inis/PCSX2_ui.ini:DEV9=/tmp/.mount_pcsx2SfJUyH/usr/lib32/pcsx2/libdev9ghzdrk-0.4.so
```

**Comment by ferion11** [comment]
Yep! The path have to change because of security of one AppImage.
Before each running, I change it to the right place:
https://github.com/ferion11/PCSX2_Appimage/blob/b0439a5bab387aef126fd3947caa3abac949d605/AppRun#L174-L182
Sorry, but I can't reproduce it yet with the AppImage. But from your screenshot, I have found that you are running it outside the AppImage, from your "$HOME/.pcsx2/pcsx2" executable.
All Appimages are made to be executed, so the command should be similar to
```
./pcsx2-v1.5.0-dev-3389-g6e22efe79-x86_64.AppImage
* make the configuration, then exit, and start again:
./pcsx2-v1.5.0-dev-3389-g6e22efe79-x86_64.AppImage
* make sure the configuration is there, then exit again, and now you can run with "nogui" options like:
./pcsx2-v1.5.0-dev-3389-g6e22efe79-x86_64.AppImage --nogui --nodisc
```
And everything should work like it should. But if you don't like the long name, just make a link:
`ln -s pcsx2-v1.5.0-dev-3389-g6e22efe79-x86_64.AppImage pcsx2`
then you can run with `./pcsx2`. But not inside the configuration path that don't exist on the first execution. Just create one folder like "$HOME/AppImage" to work instead. And make the link only after it work without one.

**Comment by casasfernando** [comment]
Not sure what you mean by "outside" the AppImage. What I'm doing at the moment is:

1- Download the AppImage file to a folder in my home directory: "$HOME/.pcsx2"
2- Rename the downloaded file to have a shorter and predictable name as you saw "pcsx2"
3- Make the file executable.
4- Run it.

The configuration path is the default one "$HOME/.config/PCSX2" while the directory where I downloaded the AppImage file is "$HOME/.pcsx2".

I didn't have any issues with other AppImage apps I'm running in the same way so far (ie: nexcloud client), but who knows.
I will follow your advice and report back.

Thanks

**Comment by ferion11** [comment]
Ok! It's normal for usage, but not for tests. The tests have to be made like it should be without modifications. Because the rename can be the issue here.

**Comment by casasfernando** [comment]
Got it. Let me test your suggestion (without renaming the AppImage file) and report back.

**Comment by casasfernando** [comment]
So I tried again following this steps:

1- Deleted pcsx2 configuration directory contents: "$HOME/.config/PCSX2"
2- Download the AppImage file to a folder in my home directory: "$HOME/.pcsx2/pcsx2-v1.5.0-dev-3389-g6e22efe79-x86_64.AppImage"
3- Made the file executable.
4- Ran it.
5- Went through the first time configuration wizard (plugins, BIOS path, etc) and saved the settings.
6- Closed pcsx2
7- Executed the AppImage again.

Same result, plugins not found and got the plugins config dialog again.

There is a checkbox in the plugins configuration dialog regarding the plugins search path. I left that checked (default). Not sure if playing with that setting would make any difference or if I should leave it as is.

I even try using a different directory for the AppImage file as you suggested, same result:

![Screenshot_2020-03-06_14-07-21](https://user-images.githubusercontent.com/15861819/76086273-0d4b1d80-5fb4-11ea-8b3b-aabbb9ace338.png)

I'm running out of ideas. I already mentioned that I'm using the AppImage on Debian 10 (Buster) and that using any other distro shouldn't make a difference but may I ask in which distro are you testing the AppImage (since you mentioned you can't repro this)?

**Comment by ferion11** [comment]
I have tested it here, using "$HOME/.pcsx2" and all worked well. The only thing that I have made was select the "SPU2-X 2.0.0" plugin on the wizard that shows up on the first execution.

Sorry but, after run it a lot of times, using many ways, I still can't reproduce it. I'm using Gentoo Linux "amd64/17.1/no-multilib" profile. So I don't have any 32bits libs on the system.

The issue or is one bash bug of your machine (try one livecd to see), or if it is in the code, it happening here:
https://github.com/ferion11/PCSX2_Appimage/blob/b0439a5bab387aef126fd3947caa3abac949d605/AppRun#L174-L186

You can try the script:
```
#!/bin/bash
PCSX2_HOME="$HOME/.config/PCSX2"
if [ -d "$PCSX2_HOME" ]; then
	for dir_i in $(find "$PCSX2_HOME" -name *.ini); do
		sed "s/=[^[]*\/usr\/lib/=AAA_CHANGED_PATH_HERE_AAA\/usr\/lib/g" "$dir_i"
	done
fi
```
To see if it is changing in your system (don't worry, the script don't change anything, it just print on the console what would be changed)

**Comment by casasfernando** [comment]
I will try the script above and report back but after looking at the code I’m also starting to suspect about my setup.

I just realized that In my system $HOME/.config/PCSX2 is not really a directory but a symlink pointing to a directory in a different path in the filesystem (/opt/retropie/configs/ps2). This is because it’s more convenient in my case to have all the config dirs for the different emulators I use in the same place (easier to sync with my Nextcloud server -long story-). So besides testing your script I will also try to remove the symlink and create a real directory instead for PCSX2 conf.
Apologize me for not mentioning this before.

Thanks.

**Comment by ferion11** [comment]
Ok! Don't worry about it.

**Comment by ferion11** [comment]
After fight with some ossv4 kernel modules compilation, and think about you using symlink. The problem and the solution come to mind. The command "find" need the flag "-L" to follow symbolic links. I will make one commit, just wait to be build.

**Comment by casasfernando** [comment]
Indeed while looking at the code and seeing the find command I immediately remember about my config folder being a symlink. Hopefully the commit you did will solve it.
I will download the latest build later tonight, test it and report back.

Thanks

**Comment by casasfernando** [comment]
BTW this line of code may also be a problem since it will test only for directories:

```
if [ -d "$PCSX2_HOME" ]; then
```

It may need to be changed to something like:

```
if [ -d "$PCSX2_HOME" || -L "$PCSX2_HOME" ]; then
```

But it needs to be tested of course.

**Comment by ferion11** [comment]
On bash script now, if your "$PCSX2_HOME" is a link, then the test "-d "$PCSX2_HOME"" will be true if the link point to a directory, but will be false if the link point to a file.
So it don't need one patch now.

**Comment by casasfernando** [comment]
Updated to the latest build and the problem is solved.
Indeed the issue was PCSX2 config dir being a symlink.

Thanks a lot for your work on this!
