### ISSUE TITLE
Audio doesn't work

### ISSUE THREAD

**Issue by ipkpjersi** [ferion11/PCSX2_Appimage#8]
I am using Ubuntu 20.04 with PulseAudio. The audio does not work on the 1.6.x or 1.7.x AppImage builds. It works on 1.5.0 provided by Ubuntu's apt repositories. 

The AppImage builds are using SPU2null 0.8.0 as the only provided audio plugin:
![](https://i.imgur.com/ihSyn5g.png)

 The 1.5.0 apt provided build is using SPU2-X-2.0.0 which works perfectly:
![](https://i.imgur.com/xIdtupd.png)

**Comment by ipkpjersi** [comment]
@ferion11 Any idea what could be causing this issue in the AppImage?

**Comment by ferion11** [comment]
> @ferion11 Any idea what could be causing this issue in the AppImage?

This AppImage will be discontinued, as the current git version is already independent of plugins and works in 64bits.
If desired, test using another more suitable setting for Pulseaudio, setting the "Module" to "SDL Audio (Recommended for PulseAudio)"

**Comment by ipkpjersi** [comment]
1) I don't think it's worth discontinuing AppImages, the current git version still relies on having the proper system libraries, does it not?
2) The SPU2-X config is only available for me in non-AppImages, the only plugin available to me in the AppImages is SPU2null 0.8.0.

**Comment by ferion11** [comment]
There will be no plugins on the next release:
https://github.com/PCSX2/pcsx2/pull/4436

and there will be one official AppImage:
https://github.com/PCSX2/pcsx2/pull/4103

you can test it using the version on the fork that got merged:
https://github.com/qurious-pixel/pcsx2/releases

Then there is no more need for this hack version anymore.

**Comment by ipkpjersi** [comment]
Oh that's good to know there will be an official AppImage, thanks.

edit: I tested https://github.com/qurious-pixel/pcsx2/commit/2df254281fe7c5cc68221e48c17ee98fabde5bb3 and audio plus everything else seems to be working perfectly, thanks.

**Comment by ipkpjersi** [comment]
I have a suggestion, maybe you should update the README and/or archive this repository so people know it is no longer needed?
